<?php

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use \Drupal\Core\Form\FormStateInterface;

/**
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 * Hide email and password field if the current user doesn't have admin users permission
 */
function social_auth_wechat_form_user_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $user = \Drupal::currentUser();
  $is_wechat_account = substr($form['account']['mail']['#default_value'], -strlen('wechat')) == 'wechat' ? true : false;
  if (!$user->hasPermission('administer users') && $is_wechat_account) {
    $form['account']['mail']['#type'] = 'hidden';
    $form['account']['pass']['#type'] = 'hidden';
    $form['account']['current_pass']['#type'] = 'hidden';
  }
}

function social_auth_wechat_entity_base_field_info(EntityTypeInterface $entity_type) {
  if ($entity_type->id() == 'social_auth') {
    $fields = [];
    $fields['provider_union_id'] = BaseFieldDefinition::create('string')
      ->setLabel(t('Provider union user ID'))
      ->setDescription(t('Some providers can create multi applications, and all the applications shared one user ID.'));

    return $fields;
  }
}
